=== valtimo-platform/valtimo/backend/case/src/main/resources/config/case/schema/case-list.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://json-schema.org/draft-07/schema#",
    "title": "Case list definition",
    "description": "Representation of a case list column definition",
    "type": "array",
    "additionalProperties": false,
    "items": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string"
            },
            "key": {
                "type": "string"
            },
            "path": {
                "type": "string"
            },
            "displayType": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string"
                    },
                    "displayTypeParameters": {
                        "type": "object"
                    }
                },
                "required": [
                    "type"
                ]
            },
            "sortable": {
                "type": "boolean"
            },
            "defaultSort": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "order": {
                "type": "integer"
            },
            "exportable": {
                "type": "boolean"
            }
        },
        "required": [
            "key",
            "path",
            "displayType",
            "sortable"
        ]
    }
}

=== valtimo-platform/valtimo/backend/app/gzac/src/dev/resources/config/case/aggregation-demo/1-0-0/case/list/aggregation-demo.case-list.json
[
  {
    "key": "createdOn",
    "path": "case:createdOn",
    "displayType": {
      "type": "date",
      "displayTypeParameters": {
        "dateFormat": null
      }
    },
    "sortable": true,
    "defaultSort": "DESC",
    "order": 0
  },
  {
    "key": "inputText",
    "path": "doc:inputText",
    "displayType": {
      "type": "text",
      "displayTypeParameters": {}
    },
    "sortable": true,
    "order": 1
  },
  {
    "key": "inputNumber",
    "path": "doc:inputNumber",
    "displayType": {
      "type": "text",
      "displayTypeParameters": {}
    },
    "sortable": true,
    "order": 2
  },
  {
    "key": "assigneeFullName",
    "path": "case:assigneeFullName",
    "displayType": {
      "type": "text",
      "displayTypeParameters": {}
    },
    "sortable": true,
    "order": 3
  }
]

=== valtimo-platform/valtimo/backend/app/gzac/src/evenementenvergunning/resources/config/case/evenementenvergunning/1-0-7/case/list/evenementenvergunning.case-list.json
[
    {
        "title": "Evenement",
        "key": "evenement",
        "path": "doc:evenementDetails.evenementNaam",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": false,
        "order": 0
    },
    {
        "title": "Type",
        "key": "evenementType",
        "path": "doc:evenementDetails.evenementType",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true,
        "order": 1
    },
    {
        "title": "Locatie",
        "key": "locatie",
        "path": "doc:locatieEnOpstelling.evenementLocatie",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": false,
        "order": 2
    },
    {
        "title": "Datum evenement",
        "key": "datum",
        "path": "doc:evenementDetails.evenementDatum",
        "displayType": {
            "type": "date",
            "displayTypeParameters": {
                "dateFormat": null
            }
        },
        "sortable": false,
        "order": 3
    },
    {
        "title": "Aanvrager",
        "key": "aanvrager",
        "path": "doc:aanvrager.naam",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": false,
        "order": 4
    },
    {
        "title": "Aanvraagdatum",
        "key": "aanvraagDatum",
        "path": "case:createdOn",
        "displayType": {
            "type": "date",
            "displayTypeParameters": {
                "dateFormat": "DD-MM-YYYY"
            }
        },
        "sortable": true,
        "defaultSort": "DESC",
        "order": 5
    },
    {
        "title": "Status",
        "key": "status",
        "path": "case:internalStatus",
        "displayType": {
            "type": "tags",
            "displayTypeParameters": {}
        },
        "sortable": false,
        "order": 6
    }
]

=== valtimo-platform/valtimo/backend/app/gzac/src/dev/resources/config/case/bezwaar/1-0-1/case/task-list/bezwaar.case-task-list.json
[
    {
        "title": "Created on",
        "key": "createTime",
        "path": "task:createTime",
        "displayType": {
            "type": "date",
            "displayTypeParameters": {
                "dateFormat": ""
            }
        },
        "sortable": true,
        "defaultSort": "DESC"
    },
    {
        "title": "Name",
        "key": "name",
        "path": "task:name",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true
    },
    {
        "title": "Assignee",
        "key": "assignee",
        "path": "task:assignee",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true
    },
    {
        "title": "Team",
        "key": "team",
        "path": "task:assignedTeamTitle",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true
    }
]

=== valtimo-platform/valtimo/backend/app/gzac/src/dev/resources/config/case/layout-test/1-0-0/case/list/layout-test.case-list.json
[
    {
        "key": "createdOn",
        "path": "case:createdOn",
        "displayType": {
            "type": "date",
            "displayTypeParameters": {
                "dateFormat": null
            }
        },
        "sortable": true,
        "defaultSort": "DESC",
        "order": 0
    },
    {
        "key": "firstName",
        "path": "doc:firstName",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true,
        "order": 1
    },
    {
        "key": "lastName",
        "path": "doc:lastName",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true,
        "order": 2
    },
    {
        "key": "assigneeFullName",
        "path": "case:assigneeFullName",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true,
        "order": 3
    }
]

=== valtimo-platform/valtimo/backend/app/gzac/src/main/resources/config/case/bezwaar/1-0-1/case/list/bezwaar.case-list.json
[
    {
        "key": "createdBy",
        "path": "case:createdBy",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true,
        "order": 0
    },
    {
        "key": "createdOn",
        "path": "case:createdOn",
        "displayType": {
            "type": "date",
            "displayTypeParameters": {
                "dateFormat": null
            }
        },
        "sortable": true,
        "defaultSort": "DESC",
        "order": 1
    },
    {
        "key": "modifiedOn",
        "path": "case:modifiedOn",
        "displayType": {
            "type": "date",
            "displayTypeParameters": {
                "dateFormat": null
            }
        },
        "sortable": true,
        "order": 2
    },
    {
        "key": "assigneeFullName",
        "path": "case:assigneeFullName",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true,
        "order": 3,
        "exportable": true
    },
    {
        "key": "status",
        "path": "case:internalStatus",
        "displayType": {
            "type": "tags",
            "displayTypeParameters": {}
        },
        "sortable": true,
        "order": 4,
        "exportable": false
    },
    {
        "key": "voornaam",
        "title": "Voornaam",
        "path": "doc:voornaam",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true,
        "order": 5,
        "exportable": true
    },
    {
        "key": "achternaam",
        "title": "Achternaam",
        "path": "doc:achternaam",
        "displayType": {
            "type": "text",
            "displayTypeParameters": {}
        },
        "sortable": true,
        "order": 6,
        "exportable": true
    },
    {
        "key": "retentionDate",
        "path": "case:retentionDate",
        "displayType": {
            "type": "date",
            "displayTypeParameters": {
                "dateFormat": null
            }
        },
        "sortable": true,
        "order": 7
    }
]
